### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by David-NF**
This is the Dutch translation for your extension, this was a easy one just two lines :) 

BUBBLEMOUSE_EXPLAIN is not literally translated, I gave it a nice touch but it still means the same.

### CODE REVIEW

**Comment by cece74** [comment]
Thank you very much!

**Comment by David-NF** [comment]
You're welcome, just to be sure... you know that you have to merge these edits before they are part of your core? It's just a patch now, that you can ad when you're ready. Keep up the good work :)

**Comment by cece74** [comment]
I know nothing. I'm new to these things. Help is well accepted. Thank you very much!

**Comment by David-NF** [comment]
Well, I'm kind of new here as well although I'm here for about 11 months I just contributed to the Dutch translation and added PR in different project. I never head a project myself or had to merge a PR into the core. I think that you should have a option to merge my PR, not sure where... I'm sorry!

**Pull request merged**
